AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  batch_system 작업 중

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  PeriodicPaymentSystemFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: periodicPaymentBatch/
      Handler: periodicPaymentBatch
      PackageType: Zip
      MemorySize: 128
      Runtime: go1.x
      VpcConfig:
        SecurityGroupIds:
          - sg-048ff7d86d1e33455 #idea_dev_private_int
        SubnetIds:
          - subnet-0f8b7b3df5e5dbfb6 #idea-private-b1
          - subnet-0ed86c9cfd4120dab #idea-private-c1
      Architectures:
        - x86_64
      Events:
        CWSchedule:
          Type: Schedule
          Properties:
            Schedule: 'cron(15 10 * * ? *)' # 매일 UTC 00:05
      ReservedConcurrentExecutions: 1
      Policies:
        - Statement:
            - Sid: SSMDescribeParametersPolicy
              Effect: Allow
              Action:
                - ssm:DescribeParameters
              Resource: '*'
            - Sid: SSMGetParameterPolicy
              Effect: Allow
              Action:
                - ssm:GetParameters
                - ssm:GetParameter
              Resource: '*'
      Environment:
        Variables:
          PROJECT: 'medical_web'
          ENV: 'dev'
          REGION: 'ap-northeast-2'

Outputs:
  PeriodicPaymentSystemFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt PeriodicPaymentSystemFunction.Arn
