AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  batch_system 작업 중

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  PeriodicPaymentSystemFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: periodicPaymentSystem/
      Handler: periodicPaymentSystem
      PackageType: Zip
      MemorySize: 128
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CWSchedule:
          Type: Schedule
          Properties:
            Schedule: 'cron(0/5 * ? * * *)' # 매일 UTC 00:05
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          PROJECT: 'medical_web'
          ENV: 'dev'
          REGION: 'ap-northeast-2'

Outputs:
  PeriodicPaymentSystemFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt PeriodicPaymentSystemFunction.Arn
